<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Project xmlns="http://schemas.microsoft.com/project">
    <Title>Project1</Title>
    <ScheduleFromStart>1</ScheduleFromStart>
    <StartDate>2013-09-24T08:00:00</StartDate>
    <FinishDate>2013-10-01T17:00:00</FinishDate>
    <FYStartDate>1</FYStartDate>
    <CriticalSlackLimit>0</CriticalSlackLimit>
    <CurrencyDigits>2</CurrencyDigits>
    <CurrencySymbol>$</CurrencySymbol>
    <CurrencySymbolPosition>0</CurrencySymbolPosition>
    <CalendarUID>1</CalendarUID>
    <DefaultStartTime>08:00:00</DefaultStartTime>
    <MinutesPerDay>480</MinutesPerDay>
    <MinutesPerWeek>2400</MinutesPerWeek>
    <DaysPerMonth>20</DaysPerMonth>
    <DefaultTaskType>0</DefaultTaskType>
    <DefaultFixedCostAccrual>2</DefaultFixedCostAccrual>
    <DefaultStandardRate>10</DefaultStandardRate>
    <DefaultOvertimeRate>15</DefaultOvertimeRate>
    <DurationFormat>7</DurationFormat>
    <WorkFormat>2</WorkFormat>
    <EditableActualCosts>0</EditableActualCosts>
    <HonorConstraints>0</HonorConstraints>
    <EarnedValueMethod>0</EarnedValueMethod>
    <InsertedProjectsLikeSummary>0</InsertedProjectsLikeSummary>
    <MultipleCriticalPaths>0</MultipleCriticalPaths>
    <NewTasksEffortDriven>0</NewTasksEffortDriven>
    <NewTasksEstimated>1</NewTasksEstimated>
    <SplitsInProgressTasks>0</SplitsInProgressTasks>
    <SpreadActualCost>0</SpreadActualCost>
    <SpreadPercentComplete>0</SpreadPercentComplete>
    <TaskUpdatesResource>1</TaskUpdatesResource>
    <FiscalYearStart>0</FiscalYearStart>
    <WeekStartDay>1</WeekStartDay>
    <MoveCompletedEndsBack>0</MoveCompletedEndsBack>
    <MoveRemainingStartsBack>0</MoveRemainingStartsBack>
    <MoveRemainingStartsForward>0</MoveRemainingStartsForward>
    <MoveCompletedEndsForward>0</MoveCompletedEndsForward>
    <BaselineForEarnedValue>0</BaselineForEarnedValue>
    <AutoAddNewResourcesAndTasks>1</AutoAddNewResourcesAndTasks>
    <CurrentDate>2013-09-23T09:57:00</CurrentDate>
    <MicrosoftProjectServerURL>1</MicrosoftProjectServerURL>
    <Autolink>1</Autolink>
    <NewTaskStartDate>0</NewTaskStartDate>
    <DefaultTaskEVMethod>0</DefaultTaskEVMethod>
    <ProjectExternallyEdited>0</ProjectExternallyEdited>
    <ActualsInSync>0</ActualsInSync>
    <RemoveFileProperties>0</RemoveFileProperties>
    <AdminProject>0</AdminProject>
    <ExtendedAttributes>
        <ExtendedAttribute>
            <FieldID>205521023</FieldID>
            <FieldName>Flag1</FieldName>
            <Alias>Developer</Alias>
        </ExtendedAttribute>
        <ExtendedAttribute>
            <FieldID>205521024</FieldID>
            <FieldName>Flag2</FieldName>
            <Alias>Design</Alias>
        </ExtendedAttribute>
        <ExtendedAttribute>
            <FieldID>205521025</FieldID>
            <FieldName>Flag3</FieldName>
            <Alias>UX</Alias>
        </ExtendedAttribute>
        <ExtendedAttribute>
            <FieldID>205521026</FieldID>
            <FieldName>Flag4</FieldName>
            <Alias>Research</Alias>
        </ExtendedAttribute>
    </ExtendedAttributes>
    <Calendars>
        <Calendar>
            <UID>1</UID>
            <Name>Standard</Name>
            <IsBaseCalendar>1</IsBaseCalendar>
            <WeekDays>
                <WeekDay>
                    <DayType>1</DayType>
                    <DayWorking>0</DayWorking>
                </WeekDay>
                <WeekDay>
                    <DayType>2</DayType>
                    <DayWorking>1</DayWorking>
                    <WorkingTimes>
                        <WorkingTime>
                            <FromTime>08:00:00</FromTime>
                            <ToTime>12:00:00</ToTime>
                        </WorkingTime>
                        <WorkingTime>
                            <FromTime>13:00:00</FromTime>
                            <ToTime>17:00:00</ToTime>
                        </WorkingTime>
                    </WorkingTimes>
                </WeekDay>
                <WeekDay>
                    <DayType>3</DayType>
                    <DayWorking>1</DayWorking>
                    <WorkingTimes>
                        <WorkingTime>
                            <FromTime>08:00:00</FromTime>
                            <ToTime>12:00:00</ToTime>
                        </WorkingTime>
                        <WorkingTime>
                            <FromTime>13:00:00</FromTime>
                            <ToTime>17:00:00</ToTime>
                        </WorkingTime>
                    </WorkingTimes>
                </WeekDay>
                <WeekDay>
                    <DayType>4</DayType>
                    <DayWorking>1</DayWorking>
                    <WorkingTimes>
                        <WorkingTime>
                            <FromTime>08:00:00</FromTime>
                            <ToTime>12:00:00</ToTime>
                        </WorkingTime>
                        <WorkingTime>
                            <FromTime>13:00:00</FromTime>
                            <ToTime>17:00:00</ToTime>
                        </WorkingTime>
                    </WorkingTimes>
                </WeekDay>
                <WeekDay>
                    <DayType>5</DayType>
                    <DayWorking>1</DayWorking>
                    <WorkingTimes>
                        <WorkingTime>
                            <FromTime>08:00:00</FromTime>
                            <ToTime>12:00:00</ToTime>
                        </WorkingTime>
                        <WorkingTime>
                            <FromTime>13:00:00</FromTime>
                            <ToTime>17:00:00</ToTime>
                        </WorkingTime>
                    </WorkingTimes>
                </WeekDay>
                <WeekDay>
                    <DayType>6</DayType>
                    <DayWorking>1</DayWorking>
                    <WorkingTimes>
                        <WorkingTime>
                            <FromTime>08:00:00</FromTime>
                            <ToTime>12:00:00</ToTime>
                        </WorkingTime>
                        <WorkingTime>
                            <FromTime>13:00:00</FromTime>
                            <ToTime>17:00:00</ToTime>
                        </WorkingTime>
                    </WorkingTimes>
                </WeekDay>
                <WeekDay>
                    <DayType>7</DayType>
                    <DayWorking>0</DayWorking>
                </WeekDay>
            </WeekDays>
        </Calendar>
    </Calendars>
    <Tasks>
        <Task>
            <UID>0</UID>
            <ID>0</ID>
            <Type>0</Type>
            <IsNull>0</IsNull>
            <WBS>0</WBS>
            <OutlineNumber>0</OutlineNumber>
            <OutlineLevel>0</OutlineLevel>
            <Priority>500</Priority>
            <Start>2013-09-24T08:00:00</Start>
            <Finish>2013-10-01T17:00:00</Finish>
            <Duration>PT64H0M0S</Duration>
            <DurationFormat>7</DurationFormat>
            <ResumeValid>0</ResumeValid>
            <EffortDriven>0</EffortDriven>
            <Recurring>0</Recurring>
            <OverAllocated>0</OverAllocated>
            <Estimated>0</Estimated>
            <Milestone>0</Milestone>
            <Summary>0</Summary>
            <Critical>1</Critical>
            <IsSubproject>0</IsSubproject>
            <IsSubprojectReadOnly>0</IsSubprojectReadOnly>
            <ExternalTask>0</ExternalTask>
            <FixedCostAccrual>3</FixedCostAccrual>
            <RemainingDuration>PT64H0M0S</RemainingDuration>
            <ConstraintType>0</ConstraintType>
            <CalendarUID>-1</CalendarUID>
            <LevelAssignments>0</LevelAssignments>
            <LevelingCanSplit>0</LevelingCanSplit>
            <IgnoreResourceCalendar>0</IgnoreResourceCalendar>
            <HideBar>0</HideBar>
            <Rollup>0</Rollup>
            <EarnedValueMethod>0</EarnedValueMethod>
            <Active>1</Active>
            <Manual>0</Manual>
        </Task>
        <Task>
            <UID>2</UID>
            <ID>1</ID>
            <Name>Boden wischen</Name>
            <Type>0</Type>
            <IsNull>0</IsNull>
            <WBS>1</WBS>
            <OutlineNumber>1</OutlineNumber>
            <OutlineLevel>1</OutlineLevel>
            <Priority>500</Priority>
            <Start>2013-09-24T08:00:00</Start>
            <Finish>2013-09-26T17:00:00</Finish>
            <Duration>PT24H0M0S</Duration>
            <DurationFormat>7</DurationFormat>
            <ResumeValid>0</ResumeValid>
            <EffortDriven>0</EffortDriven>
            <Recurring>0</Recurring>
            <OverAllocated>0</OverAllocated>
            <Estimated>0</Estimated>
            <Milestone>0</Milestone>
            <Summary>0</Summary>
            <Critical>1</Critical>
            <IsSubproject>0</IsSubproject>
            <IsSubprojectReadOnly>0</IsSubprojectReadOnly>
            <ExternalTask>0</ExternalTask>
            <FixedCostAccrual>3</FixedCostAccrual>
            <PercentComplete>0</PercentComplete>
            <RemainingDuration>PT24H0M0S</RemainingDuration>
            <ConstraintType>0</ConstraintType>
            <CalendarUID>-1</CalendarUID>
            <LevelAssignments>0</LevelAssignments>
            <LevelingCanSplit>0</LevelingCanSplit>
            <Hyperlink></Hyperlink>
            <IgnoreResourceCalendar>1</IgnoreResourceCalendar>
            <HideBar>0</HideBar>
            <Rollup>0</Rollup>
            <EarnedValueMethod>0</EarnedValueMethod>
            <Active>1</Active>
            <Manual>1</Manual>
            <ManualStart>2013-09-24T08:00:00</ManualStart>
            <ManualFinish>2013-09-26T17:00:00</ManualFinish>
            <ManualDuration>PT24H0M0S</ManualDuration>
        </Task>
        <Task>
            <UID>1</UID>
            <ID>2</ID>
            <Name>Bier einkaufen</Name>
            <Type>0</Type>
            <IsNull>0</IsNull>
            <WBS>2</WBS>
            <OutlineNumber>2</OutlineNumber>
            <OutlineLevel>1</OutlineLevel>
            <Priority>500</Priority>
            <Start>2013-09-30T08:00:00</Start>
            <Finish>2013-10-01T17:00:00</Finish>
            <Duration>PT16H0M0S</Duration>
            <DurationFormat>7</DurationFormat>
            <ResumeValid>0</ResumeValid>
            <EffortDriven>0</EffortDriven>
            <Recurring>0</Recurring>
            <OverAllocated>0</OverAllocated>
            <Estimated>0</Estimated>
            <Milestone>0</Milestone>
            <Summary>0</Summary>
            <Critical>1</Critical>
            <IsSubproject>0</IsSubproject>
            <IsSubprojectReadOnly>0</IsSubprojectReadOnly>
            <ExternalTask>0</ExternalTask>
            <FixedCostAccrual>3</FixedCostAccrual>
            <PercentComplete>0</PercentComplete>
            <RemainingDuration>PT16H0M0S</RemainingDuration>
            <ConstraintType>0</ConstraintType>
            <CalendarUID>-1</CalendarUID>
            <LevelAssignments>0</LevelAssignments>
            <LevelingCanSplit>0</LevelingCanSplit>
            <Hyperlink></Hyperlink>
            <IgnoreResourceCalendar>1</IgnoreResourceCalendar>
            <HideBar>0</HideBar>
            <Rollup>0</Rollup>
            <EarnedValueMethod>0</EarnedValueMethod>
            <Active>1</Active>
            <Manual>1</Manual>
            <ManualStart>2013-09-30T08:00:00</ManualStart>
            <ManualFinish>2013-10-01T17:00:00</ManualFinish>
            <ManualDuration>PT16H0M0S</ManualDuration>
        </Task>
    </Tasks>
    <Resources>
        <Resource>
            <UID>1</UID>
            <ID>1</ID>
            <Name>Daniel Wurst</Name>
            <Type>1</Type>
            <IsNull>0</IsNull>
            <EmailAddress>daniel.wurst@sap.com</EmailAddress>
            <MaxUnits>1</MaxUnits>
            <PeakUnits>1</PeakUnits>
            <OverAllocated>0</OverAllocated>
            <Start>2013-09-24T08:00:00</Start>
            <Finish>2013-10-01T17:00:00</Finish>
            <CanLevel>0</CanLevel>
            <StandardRateFormat>3</StandardRateFormat>
            <OvertimeRateFormat>3</OvertimeRateFormat>
            <IsGeneric>0</IsGeneric>
            <IsInactive>0</IsInactive>
            <IsEnterprise>0</IsEnterprise>
            <IsBudget>0</IsBudget>
            <AvailabilityPeriods/>
        </Resource>
        <Resource>
            <UID>2</UID>
            <ID>2</ID>
            <Name>Jaehun Jeong</Name>
            <Type>1</Type>
            <IsNull>0</IsNull>
            <EmailAddress>hans.wurst@sapc.com</EmailAddress>
            <MaxUnits>1</MaxUnits>
            <PeakUnits>1</PeakUnits>
            <OverAllocated>0</OverAllocated>
            <Start>2013-09-30T08:00:00</Start>
            <Finish>2013-10-01T17:00:00</Finish>
            <CanLevel>0</CanLevel>
            <StandardRateFormat>3</StandardRateFormat>
            <OvertimeRateFormat>3</OvertimeRateFormat>
            <IsGeneric>0</IsGeneric>
            <IsInactive>0</IsInactive>
            <IsEnterprise>0</IsEnterprise>
            <IsBudget>0</IsBudget>
            <AvailabilityPeriods/>
        </Resource>
        <Resource>
            <UID>3</UID>
            <ID>3</ID>
            <Name>Julien Altieri</Name>
            <Type>1</Type>
            <IsNull>0</IsNull>
            <EmailAddress>julien.altieri@sap.com</EmailAddress>
            <MaxUnits>1</MaxUnits>
            <PeakUnits>1</PeakUnits>
            <OverAllocated>0</OverAllocated>
            <CanLevel>0</CanLevel>
            <StandardRateFormat>3</StandardRateFormat>
            <OvertimeRateFormat>3</OvertimeRateFormat>
            <IsGeneric>0</IsGeneric>
            <IsInactive>0</IsInactive>
            <IsEnterprise>0</IsEnterprise>
            <ExtendedAttribute>
                <FieldID>205521023</FieldID>
                <Value>1</Value>
            </ExtendedAttribute>
            <IsBudget>0</IsBudget>
            <AvailabilityPeriods/>
        </Resource>
        <Resource>
            <UID>4</UID>
            <ID>4</ID>
            <Name>Thomas Arends</Name>
            <Type>1</Type>
            <IsNull>0</IsNull>
            <EmailAddress>thomas.arends@sap.com</EmailAddress>
            <MaxUnits>1</MaxUnits>
            <PeakUnits>1</PeakUnits>
            <OverAllocated>0</OverAllocated>
            <CanLevel>0</CanLevel>
            <StandardRateFormat>3</StandardRateFormat>
            <OvertimeRateFormat>3</OvertimeRateFormat>
            <IsGeneric>0</IsGeneric>
            <IsInactive>0</IsInactive>
            <IsEnterprise>0</IsEnterprise>
            <IsBudget>0</IsBudget>
            <AvailabilityPeriods/>
        </Resource>
        <Resource>
            <UID>5</UID>
            <ID>5</ID>
            <Name>Sarah Deng</Name>
            <Type>1</Type>
            <IsNull>0</IsNull>
            <EmailAddress>sarah.deng@sap.com</EmailAddress>
            <MaxUnits>1</MaxUnits>
            <PeakUnits>1</PeakUnits>
            <OverAllocated>0</OverAllocated>
            <CanLevel>0</CanLevel>
            <StandardRateFormat>3</StandardRateFormat>
            <OvertimeRateFormat>3</OvertimeRateFormat>
            <IsGeneric>0</IsGeneric>
            <IsInactive>0</IsInactive>
            <IsEnterprise>0</IsEnterprise>
            <IsBudget>0</IsBudget>
            <AvailabilityPeriods/>
        </Resource>
        <Resource>
            <UID>6</UID>
            <ID>6</ID>
            <Name>Eliad Goldwasser</Name>
            <Type>1</Type>
            <IsNull>0</IsNull>
            <EmailAddress>eliad.goldwasser@sap.com</EmailAddress>
            <MaxUnits>1</MaxUnits>
            <PeakUnits>1</PeakUnits>
            <OverAllocated>0</OverAllocated>
            <CanLevel>0</CanLevel>
            <StandardRateFormat>3</StandardRateFormat>
            <OvertimeRateFormat>3</OvertimeRateFormat>
            <IsGeneric>0</IsGeneric>
            <IsInactive>0</IsInactive>
            <IsEnterprise>0</IsEnterprise>
            <IsBudget>0</IsBudget>
            <AvailabilityPeriods/>
        </Resource>
        <Resource>
            <UID>7</UID>
            <ID>7</ID>
            <Name>Laura Gomez</Name>
            <Type>1</Type>
            <IsNull>0</IsNull>
            <EmailAddress>laura.gomez@sap.com</EmailAddress>
            <MaxUnits>1</MaxUnits>
            <PeakUnits>1</PeakUnits>
            <OverAllocated>0</OverAllocated>
            <CanLevel>0</CanLevel>
            <StandardRateFormat>3</StandardRateFormat>
            <OvertimeRateFormat>3</OvertimeRateFormat>
            <IsGeneric>0</IsGeneric>
            <IsInactive>0</IsInactive>
            <IsEnterprise>0</IsEnterprise>
            <IsBudget>0</IsBudget>
            <AvailabilityPeriods/>
        </Resource>
        <Resource>
            <UID>8</UID>
            <ID>8</ID>
            <Name>Jared Hu</Name>
            <Type>1</Type>
            <IsNull>0</IsNull>
            <EmailAddress>Jared.hu@sap.com</EmailAddress>
            <MaxUnits>1</MaxUnits>
            <PeakUnits>1</PeakUnits>
            <OverAllocated>0</OverAllocated>
            <CanLevel>0</CanLevel>
            <StandardRateFormat>3</StandardRateFormat>
            <OvertimeRateFormat>3</OvertimeRateFormat>
            <IsGeneric>0</IsGeneric>
            <IsInactive>0</IsInactive>
            <IsEnterprise>0</IsEnterprise>
            <IsBudget>0</IsBudget>
            <AvailabilityPeriods/>
        </Resource>
    </Resources>
    <Assignments>
        <Assignment>
            <UID>0</UID>
            <TaskUID>2</TaskUID>
            <ResourceUID>1</ResourceUID>
            <Finish>2013-09-26T17:00:00</Finish>
            <HasFixedRateUnits>1</HasFixedRateUnits>
            <FixedMaterial>0</FixedMaterial>
            <RemainingWork>PT24H0M0S</RemainingWork>
            <Start>2013-09-24T08:00:00</Start>
            <Units>0.5</Units>
            <Work>PT24H0M0S</Work>
        </Assignment>
        <Assignment>
            <UID>1</UID>
            <TaskUID>1</TaskUID>
            <ResourceUID>1</ResourceUID>
            <Finish>2013-10-01T17:00:00</Finish>
            <HasFixedRateUnits>1</HasFixedRateUnits>
            <FixedMaterial>0</FixedMaterial>
            <RemainingWork>PT16H0M0S</RemainingWork>
            <Start>2013-09-30T08:00:00</Start>
            <Units>0.5</Units>
            <Work>PT16H0M0S</Work>
        </Assignment>
        <Assignment>
            <UID>2</UID>
            <TaskUID>1</TaskUID>
            <ResourceUID>2</ResourceUID>
            <Finish>2013-10-01T17:00:00</Finish>
            <HasFixedRateUnits>1</HasFixedRateUnits>
            <FixedMaterial>0</FixedMaterial>
            <RemainingWork>PT16H0M0S</RemainingWork>
            <Start>2013-09-30T08:00:00</Start>
            <Units>0.5</Units>
            <Work>PT16H0M0S</Work>
        </Assignment>
    </Assignments>
</Project>
